export const CHALLENGE_CATEGORIES: string[] = [
  'Gear & Transmisi',
  'Komponen Mesin',
  'Moulding & Cetakan',
  'Prototipe Produk',
  'Elektronika',
  'Robotika',
  'Otomasi & PLC',
  'IoT & Sensor',
  'Pemrosesan Material',
  'Manufaktur CNC',
  'Pengelasan & Fabrikasi',
  'Konstruksi & Struktur',
  'Arsitektur',
  'Desain Produk',
  'Ergonomi & Human Factors',
  'Automotif',
  'Aerospace',
  'Perkapalan & Offshore',
  'Energi & Kelistrikan',
  'Energi Terbarukan',
  'HVAC & Termal',
  'Fluida & Hidrolik',
  'Pneumatik',
  'Instrumentasi',
  'Kontrol & Mekatronika',
  'Medis & Alat Kesehatan',
  'Peralatan Lab',
  'Pertanian & Agro',
  'Pertambangan',
  'Tekstil & Pangan',
  'Logistik & Rantai Pasok',
  'Pengemasan',
  'Keselamatan Kerja (K3)',
  'Simulasi & Analisis (FEA/CFD)',
  'Perangkat Lunak CAD/CAE',
  'Sustainability & Daur Ulang',
  'Smart City',
  'Peralatan Rumah Tangga',
  'Mainan & Hobi',
  'Lainnya'
];

export const LIBRARY_CATEGORIES: string[] = [
  'Komponen Mesin',
  'Prototipe Produk',
  'Arsitektur',
  'Karakter',
  'Elektronika',
  'Robotika',
  'Otomasi & PLC',
  'IoT & Sensor',
  'Manufaktur CNC',
  'Konstruksi & Struktur',
  'Automotif',
  'Aerospace',
  'Perkapalan & Offshore',
  'Energi & Kelistrikan',
  'HVAC & Termal',
  'Fluida & Hidrolik',
  'Pneumatik',
  'Instrumentasi',
  'Medis & Alat Kesehatan',
  'Peralatan Lab',
  'Pertanian & Agro',
  'Pengemasan',
  'Peralatan Rumah Tangga',
  'Mainan & Hobi',
  'Seni & Kreatif',
  'Lainnya'
];


